// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phase_1.Data;

#nullable disable

namespace phase_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629113531_AddMatchSeed")]
    partial class AddMatchSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("phase_1.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mona.ahmed@example.com",
                            FailedLoginAttempts = 0,
                            FullName = "Mona Ahmed Abdelrahman",
                            IsEmailVerified = true,
                            IsPhoneVerified = true,
                            LastLoginAt = new DateTime(2026, 4, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "seed-password-hash",
                            Phone = "01010000001",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 14, 11, 15, 0, 0, DateTimeKind.Utc),
                            Email = "youssef.mohamed@example.com",
                            FailedLoginAttempts = 0,
                            FullName = "Youssef Mohamed Elsayed",
                            IsEmailVerified = true,
                            IsPhoneVerified = true,
                            LastLoginAt = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "seed-password-hash",
                            Phone = "01010000002",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 18, 8, 45, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.khaled@example.com",
                            FailedLoginAttempts = 0,
                            FullName = "Ahmed Khaled Mansour",
                            IsEmailVerified = true,
                            IsPhoneVerified = true,
                            LastLoginAt = new DateTime(2026, 4, 15, 10, 20, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "seed-password-hash",
                            Phone = "01010000003",
                            Role = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            Email = "salma.tarek@example.com",
                            FailedLoginAttempts = 0,
                            FullName = "Salma Tarek Hassan",
                            IsEmailVerified = true,
                            IsPhoneVerified = true,
                            LastLoginAt = new DateTime(2026, 4, 16, 9, 10, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "seed-password-hash",
                            Phone = "01010000004",
                            Role = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EstimatedPriceMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("EstimatedPriceMin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NeedsSupervisorApproval")
                        .HasColumnType("bit");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TreatmentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TreatmentCategoryId");

                    b.HasIndex("PatientUserId", "Status", "CreatedAt");

                    b.HasIndex("Status", "Governorate", "City", "ServiceTypeId", "CreatedAt");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Seventh District",
                            City = "Nasr City",
                            CreatedAt = new DateTime(2026, 4, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The family is looking for a supervised dental student to help with examination, preventive guidance, and a treatment plan for a 6-year-old child.",
                            EstimatedPriceMax = 250.00m,
                            EstimatedPriceMin = 180.00m,
                            Governorate = "Cairo",
                            NeedsSupervisorApproval = true,
                            PatientUserId = 1,
                            ServiceTypeId = 1,
                            Status = 2,
                            Title = "Follow-up for a child with multiple dental caries",
                            TreatmentCategoryId = 1,
                            Urgency = 2
                        },
                        new
                        {
                            Id = 2,
                            Area = "Zahraa El Maadi",
                            City = "Maadi",
                            CreatedAt = new DateTime(2026, 4, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The patient needs an in-clinic supervised student for assessment and restoration planning for painful posterior teeth.",
                            EstimatedPriceMax = 320.00m,
                            EstimatedPriceMin = 220.00m,
                            Governorate = "Cairo",
                            NeedsSupervisorApproval = true,
                            PatientUserId = 2,
                            ServiceTypeId = 2,
                            Status = 1,
                            Title = "Restorative dental treatment for damaged molars",
                            TreatmentCategoryId = 2,
                            Urgency = 3
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique();

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Giza",
                            Name = "Faculty of Dentistry",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "El Azareeta",
                            Name = "Faculty of Dentistry",
                            UniversityId = 2
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<bool>("PhoneContactOnly")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2)");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("PatientUserId");

                    b.HasIndex("StudentUserId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedAt = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            CaseId = 1,
                            CreatedAt = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            OfferId = 1,
                            PatientUserId = 1,
                            PhoneContactOnly = true,
                            Status = 1,
                            StudentUserId = 3
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("phase_1.DAL.Models.NoShowStrike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("SessionId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("NoShowStrikes");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedSessionsCount")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<decimal?>("ProposedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "StudentUserId")
                        .IsUnique();

                    b.HasIndex("StudentUserId", "Status", "CreatedAt");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedSessionsCount = 3,
                            Message = "أقترح البدء بتقييم داخل العيادة ثم جلستين علاجيتين حسب نتيجة الفحص.",
                            ProposedPrice = 220.00m,
                            Status = 2,
                            StudentUserId = 3
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Phone");

                    b.HasIndex("UserId");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("phase_1.DAL.Models.PatientProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserId");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Notes = "Young child who needs regular follow-up for articulation and communication skills."
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = new DateTime(1988, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Notes = "Needs speech rehabilitation sessions after a stroke with family support."
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ScheduledAt");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportedId")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandledByAdminId");

                    b.HasIndex("ReportedId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedUserId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("MatchId", "ReviewerUserId", "ReviewedUserId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Home Visit"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "In-Clinic Session"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Online Follow-Up"
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicRoom")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("SupervisorUserId");

                    b.HasIndex("MatchId", "Number")
                        .IsUnique();

                    b.HasIndex("MatchId", "StartAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("phase_1.DAL.Models.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("ClinicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CompletedCasesCount")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredCasesCount")
                        .HasColumnType("int");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("IsVerified");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasFilter("[StudentCode] IS NOT NULL");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            AcademicYear = 4,
                            ClinicName = "Kasr Al-Ainy Teaching Dental Clinic",
                            CompletedCasesCount = 5,
                            FacultyId = 1,
                            IsVerified = true,
                            RequiredCasesCount = 8,
                            StudentCode = "CAI-DEN-2401",
                            SupervisorName = "Dr. Hala Samir",
                            VerifiedAt = new DateTime(2026, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 4,
                            AcademicYear = 3,
                            ClinicName = "Alexandria University Dental Hospital",
                            CompletedCasesCount = 3,
                            FacultyId = 2,
                            IsVerified = true,
                            RequiredCasesCount = 6,
                            StudentCode = "ALX-DEN-1732",
                            SupervisorName = "Dr. Naglaa Adel",
                            VerifiedAt = new DateTime(2026, 2, 5, 10, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.TreatmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TreatmentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dental care cases for children, including preventive treatment and early interventions.",
                            IsActive = true,
                            Name = "Pediatric Dentistry"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cases involving fillings, simple restorations, and treatment plans to repair tooth structure.",
                            IsActive = true,
                            Name = "Restorative Dentistry"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cases that may require extractions or minor oral surgical procedures under supervision.",
                            IsActive = true,
                            Name = "Oral Surgery"
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Governorate = "Cairo",
                            Name = "Cairo University"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Governorate = "Alexandria",
                            Name = "Alexandria University"
                        });
                });

            modelBuilder.Entity("phase_1.DAL.Models.Case", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "PatientUser")
                        .WithMany("CasesPosted")
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ServiceType", "ServiceType")
                        .WithMany("Cases")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.TreatmentCategory", "TreatmentCategory")
                        .WithMany("Cases")
                        .HasForeignKey("TreatmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientUser");

                    b.Navigation("ServiceType");

                    b.Navigation("TreatmentCategory");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Conversation", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Match", "Match")
                        .WithOne("Conversation")
                        .HasForeignKey("phase_1.DAL.Models.Conversation", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Faculty", b =>
                {
                    b.HasOne("phase_1.DAL.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Match", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Case", "Case")
                        .WithMany("Matches")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.Offer", "Offer")
                        .WithOne("Match")
                        .HasForeignKey("phase_1.DAL.Models.Match", "OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "PatientUser")
                        .WithMany("PatientMatches")
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "StudentUser")
                        .WithMany("StudentMatches")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Offer");

                    b.Navigation("PatientUser");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Message", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "ReceiverUser")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "SenderUser")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("phase_1.DAL.Models.NoShowStrike", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Session", "Session")
                        .WithOne("NoShowStrike")
                        .HasForeignKey("phase_1.DAL.Models.NoShowStrike", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "User")
                        .WithMany("NoShowStrikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Offer", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Case", "Case")
                        .WithMany("Offers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "StudentUser")
                        .WithMany("OffersMade")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("phase_1.DAL.Models.OtpCode", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "User")
                        .WithMany("OtpCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("phase_1.DAL.Models.PatientProfile", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("phase_1.DAL.Models.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phase_1.DAL.Models.RefreshToken", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Reminder", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Session", "Session")
                        .WithMany("Reminders")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Report", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "HandledByAdmin")
                        .WithMany("ReportsHandled")
                        .HasForeignKey("HandledByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "Reported")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "Reporter")
                        .WithMany("ReportsMade")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandledByAdmin");

                    b.Navigation("Reported");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Review", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Match", "Match")
                        .WithMany("Reviews")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "ReviewerUser")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("ReviewedUser");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Session", b =>
                {
                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "CancelledByUser")
                        .WithMany("SessionsCancelled")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("phase_1.DAL.Models.Match", "Match")
                        .WithMany("Sessions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "SupervisorUser")
                        .WithMany("SessionsSupervised")
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CancelledByUser");

                    b.Navigation("Match");

                    b.Navigation("SupervisorUser");
                });

            modelBuilder.Entity("phase_1.DAL.Models.StudentProfile", b =>
                {
                    b.HasOne("phase_1.DAL.Models.Faculty", "Faculty")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phase_1.DAL.Models.ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("phase_1.DAL.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("phase_1.DAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("CasesPosted");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("NoShowStrikes");

                    b.Navigation("OffersMade");

                    b.Navigation("OtpCodes");

                    b.Navigation("PatientMatches");

                    b.Navigation("PatientProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportsHandled");

                    b.Navigation("ReportsMade");

                    b.Navigation("ReportsReceived");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("SessionsCancelled");

                    b.Navigation("SessionsSupervised");

                    b.Navigation("StudentMatches");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Case", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Faculty", b =>
                {
                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Match", b =>
                {
                    b.Navigation("Conversation");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Offer", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("phase_1.DAL.Models.ServiceType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("phase_1.DAL.Models.Session", b =>
                {
                    b.Navigation("NoShowStrike");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("phase_1.DAL.Models.TreatmentCategory", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("phase_1.DAL.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
